---
src_vocab: '/home/s.ang/nmt_cs6101/data/iwslt_2015_en_vn/vocab.en'
dst_vocab: '/home/s.ang/nmt_cs6101/data/iwslt_2015_en_vn/vocab.vi'
src_vocab_size: 17191
dst_vocab_size: 7709
hidden_units: 512
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
binding_embedding: False
train:
    logdir: './log/'
    dis_src_vocab: '/home/s.ang/nmt_cs6101/data/iwslt_2015_en_vn/vocab.en' 
    dis_dst_vocab: '/home/s.ang/nmt_cs6101/data/iwslt_2015_en_vn/vocab.vi'
    dis_max_epoches: 2
    dis_dispFreq: 1
    dis_saveFreq: 100
    dis_devFreq: 100
    dis_batch_size: 100
    dis_saveto: './run.1'
    dis_reshuffle: True
    dis_gpu_device: 'gpu-0-1-2-3-4-5-6-7'
    dis_max_len: 50
    dis_positive_data: './pretrain/target_bpe_u8.txt_lf_50_1011200'
    dis_negative_data: './pretrain/negative_bpe_u8.txt'
    dis_source_data: './pretrain/source_bpe_u8.txt_lf_50_1011200'
    dis_dev_positive_data: './pretrain/dis_dev_positive_data'
    dis_dev_negative_data: './pretrain/dis_dev_negative_data'
    dis_dev_source_data: './pretrain/dis_dev_source_data'
    dis_reload: True
    dis_clip_c: 1.0
    dis_dim_word: 512
    dis_optimizer: 'rmsprop'
    dis_scope: 'discnn'
